ALTER TABLE turnos DROP FOREIGN KEY OT;
ALTER TABLE odontologos MODIFY COLUMN id INT AUTO_INCREMENT;
ALTER TABLE turnos ADD CONSTRAINT OT FOREIGN KEY (odontologo) REFERENCES odontologos(id);

ALTER TABLE turnos DROP FOREIGN KEY OT;
ALTER TABLE "paciente" MODIFY COLUMN id INT AUTO_INCREMENT;
ALTER TABLE turnos ADD CONSTRAINT OT FOREIGN KEY (odontologo) REFERENCES odontologos(id);

